name: Build anixart_ios IPA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Package IPA
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode Project
        run: xcodegen generate

      - name: Build and Archive
        run: |
          xcodebuild archive \
            -project "anixart_ios.xcodeproj" \
            -scheme "anixart_ios" \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY=""

      - name: Manually Package IPA for Sideloadly
        run: |
          mkdir -p build/ipa/Payload
          cp -r build/App.xcarchive/Products/Applications/*.app build/ipa/Payload/
          cd build/ipa
          zip -r anixart_ios.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: anixart_ios-ipa
          path: build/ipa/anixart_ios.ipa 
          retention-days: 7
