name: Build iOS unsigned IPA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Позволяет запускать сборку вручную из вкладки Actions

jobs:
  build:
    name: Build and Export IPA
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Выбираем актуальную версию Xcode (по умолчанию на macos-latest стоит стабильная)
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Create ExportOptions.plist
        run: |
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF

      - name: Build and Archive
        run: |
          xcodebuild archive \
            -project "anixart_ios.xcodeproj" \
            -scheme "anixart_ios" \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY=""

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportPath $PWD/build/ipa \
            -exportOptionsPlist ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY=""

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/ipa/*.ipa
          retention-days: 7
